CREATE SEQUENCE IF NOT EXISTS contacts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_table_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE contacts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT,
    email     VARCHAR(255),
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    phone     VARCHAR(255),
    telegram  VARCHAR(255),
    CONSTRAINT contacts_pkey PRIMARY KEY (id)
);

CREATE TABLE user_table
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password VARCHAR(255),
    role     VARCHAR(255),
    username VARCHAR(255)                            NOT NULL,
    CONSTRAINT user_table_pkey PRIMARY KEY (id)
);

ALTER TABLE user_table
    ADD CONSTRAINT user_table_username_key UNIQUE (username);

ALTER TABLE contacts
    ADD CONSTRAINT fkjvi5wwu1lht79ird63ghgojea FOREIGN KEY (user_id) REFERENCES user_table (id) ON DELETE NO ACTION;